### ISSUE TITLE
fails on ie11 (surface 2)

### ISSUE THREAD

**Issue by cthedot** [glslio/glsl-transition#2]
Somehow not even the drop down is properly initialized. Running the test on RT desktop ie11 gives two javascript errors:

File test: Object doesn't support property or method 'setup'

Not sure about this. Mocha.setup should be there if mocha works in general. Sadly console mocha returns the div id="mocha"... but actually just saw mocha gives a 404?

File bundle.j's, 9608: 'describe' is undefined, may be result of first error though...

**Comment by gre** [comment]
Just released a new version of glsl-transition.
there is no more tests for now since the codebase is very small and mostly rely on `gl-shader` (not much to test).
The new library version should be simpler to use and more robust and efficient.

If WebGL related similar bugs appear in the future, issues should now be raised on `gl-shader` instead – but I guess this was caused by webgl-debug.

Regards
